"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var text = "sample text";
console.log(text);
var num = 25.60;
console.log(num);
var bol = true;
console.log(bol);
var bol1 = false;
console.log(bol1);
